export const techIconMap: Record<string, { icon: string }> = {
  "Adobe": { icon: "https://www.adobe.com/favicon.ico" },
  "Altium": { icon: "https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/altiumdesigner.svg" },
  "Apache Spark": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apachespark/apachespark-original.svg" },
  "Arduino": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/arduino/arduino-original.svg" },
  "Assembly": { icon: "/tech-stack-icons/assembly.svg" },
  "Autodesk": { icon: "https://www.autodesk.com/favicon.ico" },
  "AWS": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-plain-wordmark.svg" },
  "C": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/c/c-original.svg" },
  "C#": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-original.svg" },
  "C++": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg" },
  "Canva": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/canva/canva-original.svg" },
  "Chart.js": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/chartjs/chartjs-original.svg" },
  "Clerk": { icon: "https://avatars.githubusercontent.com/u/49538330?s=200&v=4" },
  "Cloudinary": { icon: "/tech-stack-icons/cloudinary.svg" },
  "CSS": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg" },
  "Docker": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg" },
  "Express.js": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg" },
  "FastAPI": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/fastapi/fastapi-original.svg" },
  "Figma": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg" },
  "Firebase": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg" },
  "Flask": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flask/flask-original.svg" },
  "FPGA Tools": { icon: "/tech-stack-icons/vivado.svg" },
  "Framer Motion": { icon: "https://avatars.githubusercontent.com/u/42876?s=200&v=4" },
  "Framer": { icon: "https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/framer.svg" },
  "General Transit Feed Specification": { icon: "/tech-stack-icons/general-transit-feed-specification.svg" },
  "Git": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg" },
  "Go": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/go/go-original-wordmark.svg" },
  "Godot": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/godot/godot-original.svg" },
  "Google Cloud": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg" },
  "HTML": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg" },
  "Java": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg" },
  "JavaScript": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg" },
  "Kubernetes": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kubernetes/kubernetes-original.svg" },
  "LangChain": { icon: "https://avatars.githubusercontent.com/u/126733545?s=200&v=4" },
  "LangGraph": { icon: "https://avatars.githubusercontent.com/u/126733545?s=200&v=4" },
  "libGDX": { icon: "/tech-stack-icons/libGDX.svg" },
  "Mapbox": { icon: "https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/mapbox.svg" },
  "Markdown": { icon: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/markdown.svg" },
  "Material UI": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/materialui/materialui-original.svg" },
  "MATLAB": { icon: "/tech-stack-icons/matlab.svg" },
  "Matplotlib": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/matplotlib/matplotlib-original.svg" },
  "MongoDB": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg" },
  "Next.js": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg" },
  "Node.js": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg" },
  "NumPy": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/numpy/numpy-original.svg" },
  "OpenTripPlanner": { icon: "/tech-stack-icons/opentripplanner.svg" },
  "pandas": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pandas/pandas-original.svg" },
  "Plaid": { icon: "/tech-stack-icons/plaid.svg" },
  "PokéAPI": { icon: "https://raw.githubusercontent.com/PokeAPI/media/master/logo/pokeapi_256.png" },
  "PostgreSQL": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg" },
  "Prisma": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/prisma/prisma-original.svg" },
  "Python": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg" },
  "PyTorch": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pytorch/pytorch-original.svg" },
  "Qt": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/qt/qt-original.svg" },
  "Radix UI": { icon: "https://avatars.githubusercontent.com/u/75042455?s=200&v=4" },
  "React Aria": { icon: "/tech-stack-icons/react-aria.svg" },
  "React": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" },
  "Redis": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redis/redis-original.svg" },
  "Replicate": { icon: "/tech-stack-icons/replicate.svg" },
  "Rust": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rust/rust-original.svg" },
  "scikit-learn": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/scikitlearn/scikitlearn-original.svg" },
  "shadcn": { icon: "https://avatars.githubusercontent.com/u/139895814?s=200&v=4" },
  "SPICE": { icon: "/tech-stack-icons/ltspice.svg" },
  "Spline": { icon: "/tech-stack-icons/spline.svg" },
  "Spring Boot": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg" },
  "SQL": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azuresqldatabase/azuresqldatabase-original.svg" },
  "SQLite": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sqlite/sqlite-original.svg" },
  "Storybook": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/storybook/storybook-original.svg" },
  "Streamlit": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/streamlit/streamlit-original.svg" },
  "Supabase": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/supabase/supabase-original.svg" },
  "Swift": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg" },
  "SwiftUI": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg" },
  "Tailwind CSS": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg" },
  "TensorFlow": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tensorflow/tensorflow-original.svg" },
  "Three.js": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/threejs/threejs-original.svg" },
  "TypeScript": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg" },
  "Unity": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/unity/unity-original.svg" },
  "Verilog": { icon: "/tech-stack-icons/verilog.svg" },
  "Vite": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vitejs/vitejs-original.svg" },
  "Vue.js": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg" },
  "WebSockets": { icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/socketio/socketio-original.svg" },
}

export function getTechIcon(tag: string) {
  return techIconMap[tag] ?? null
}